### ISSUE TITLE
One more tablist issue

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#27]
So sometimes when you go into the categories like Movement, Render, Combat etc. it crashes
And always gives this error log

`java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.mymonsterdk.destro.overlay.TabGui1.getCurrentModule(TabGui1.java:73)
	at com.mymonsterdk.destro.overlay.TabGui1.renderMenu(TabGui1.java:409)
	at com.mymonsterdk.destro.overlay.TabGui1.renderModules(TabGui1.java:366)
	at com.mymonsterdk.destro.overlay.TabGui1.onRender2D(TabGui1.java:120)
	at com.mymonsterdk.destro.event.EventManager.call(EventManager.java:112)
	at net.minecraft.client.gui.GuiIngame.renderGameOverlay(GuiIngame.java:152)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1114)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1033)
	at net.minecraft.client.Minecraft.run(Minecraft.java:450)
	at net.minecraft.client.main.Main.main(Main.java:108)
	at Start.main(Start.java:11)`

**Comment by OxideWaveLength** [comment]
The fix is pretty easy, you can replace the method TabGUI1#getCurrentModule() with the following code

``` Java
private Module getCurrentModule() {
	int modulesSize = getModules().size();
	if(modulesSize <= currentModule)
		currentModule = modulesSize;

	return getModules().get(currentModule);
}
```

If the issue persists, you can re-open this issue
