### ISSUE TITLE
Exported client bug

### ISSUE THREAD

**Issue by Jefferson88999** [OxideWaveLength/Minecraft-Hack-BaseClient#50]
So i exported my client, added the json, but when i try to launch it i get an error saying Exit code: 0.
Both my edited version as the default version have this issue.

**Comment by OxideWaveLength** [comment]
Could you attach the logs, making sure to strip out your token

**Comment by Jefferson88999** [comment]
18:21:15.279
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
18:21:15.279
at net.minecraft.util.StatCollector.<clinit>(StatCollector.java:4)
18:21:15.279
at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:267)
18:21:15.279
at net.minecraft.item.Item.getItemStackDisplayName(Item.java:379)
18:21:15.279
at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:506)
18:21:15.279
at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:848)
18:21:15.279
at net.minecraft.stats.StatList.initMiningStats(StatList.java:175)
18:21:15.279
at net.minecraft.stats.StatList.init(StatList.java:127)
18:21:15.279
at net.minecraft.init.Bootstrap.register(Bootstrap.java:434)
18:21:15.279
at net.minecraft.client.Minecraft.<init>(Minecraft.java:407)
18:21:15.279
at net.minecraft.client.main.Main.main(Main.java:108)
18:21:15.279
Caused by: java.lang.NullPointerException
18:21:15.279
at java.io.Reader.<init>(Reader.java:78)
18:21:15.279
at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
18:21:15.279
at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
18:21:15.279
at net.minecraft.util.StringTranslate.<init>(StringTranslate.java:42)
18:21:15.279
at net.minecraft.util.StringTranslate.<clinit>(StringTranslate.java:30)
18:21:15.279
... 10 more
18:21:15.341
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
18:21:15.376
Process crashed with exit code 1

**Comment by OxideWaveLength** [comment]
It seems like you haven't copied correctly the assets folder. If you have copied the "assets" folder from the 1.8.8-Optifine jar into your client's exported jar make sure that the file "en_US.lang", that can be found under the path "assets/minecraft/lang" is there

**Comment by Jefferson88999** [comment]
Yes, this seems to have fixed it. I completely overlooked this step.
Thank you.

**Comment by OxideWaveLength** [comment]
You haven't, I forgot to add it and I apologize; I'm glad that you got it working now, though
