### ISSUE TITLE
Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path: /home/xelly/Downloads/Build 910/jars/versions/1.8/1.8-natives 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818) 	at java.base/java.lang.System.loadLibrary(System.java:1989) 	at org.lwjgl.Sys$1.run(Sys.java:73) 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) 	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) 	at org.lwjgl.Sys.loadLibrary(Sys.java:95) 	at org.lwjgl.Sys.<clinit>(Sys.java:112) 	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2602) 	at net.minecraft.util.Timer.<init>(Timer.java:59) 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:231) 	at net.minecraft.client.main.Main.main(Main.java:108) 	at Start.main(Start.java:7)

### ISSUE THREAD

**Issue by xellylol** [OxideWaveLength/Minecraft-Hack-BaseClient#96]
Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path: /home/xelly/Downloads/Build 910/jars/versions/1.8/1.8-natives
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2602)
	at net.minecraft.util.Timer.<init>(Timer.java:59)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:231)
	at net.minecraft.client.main.Main.main(Main.java:108)
	at Start.main(Start.java:7)

fixxxxxx plzzzz

**Comment by josephworks** [comment]
Check your project structure or build path

**Comment by OxideWaveLength** [comment]
Closing due to inactivity.
