### ISSUE TITLE
lwjgl64 error

### ISSUE THREAD

**Issue by CColdFox** [OxideWaveLength/Minecraft-Hack-BaseClient#98]
When trying to run/debug the client, this error occurs:

`Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:2602)
	at net.minecraft.util.Timer.<init>(Timer.java:59)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:231)
	at net.minecraft.client.main.Main.main(Main.java:108)
	at Start.main(Start.java:7)
`
I saw the wiki and checked the fix for this, but the working directory is already in "MCPLOC/jars", so I don't know what to do. If that can help, my IDE is Eclipse.

**Comment by josephworks** [comment]
Be sure to add your 1.8.8-natives to the IntelliJ project structure as a
dependency.  The error is saying that it cannot locate Minecraft natives,
specifically lwjgl.

**Comment by CColdFox** [comment]
Sorry, can you maybe tell me how to do that on Eclipse?

**Comment by josephworks** [comment]
Oh, I forgot.

**Comment by CColdFox** [comment]
I fixed the problem.
For everyone else having this same exact problem, download a ready-to-go MCP 1.8.8. You can find this on GitHub easily. For my case, the batch file did not installed everything correctly.
